<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Gublu" ignored="0" tests="4" failures="1" timestamp="02 Apr 2018 21:52:14 GMT" time="0.041" errors="0">
  <testcase name="LoginTest" time="0.005" classname="AppliTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [B] but found [A]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [B] but found [A]
at AppliTest.LoginTest(AppliTest.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="passchTest" time="0.001" classname="AppliTest">
    <skipped/>
  </testcase> <!-- passchTest -->
  <testcase name="logoutTest" time="0.0" classname="AppliTest"/>
  <testcase name="LoginTest1" time="0.0" classname="AppliTest"/>
</testsuite>
